### ISSUE TITLE
add-path

### ISSUE THREAD

**Issue by rawlins** [alexjurkiewicz/setup-ccache#2]
Looks like this action is impacted by the add-path deprecation (which finally moved from warning to disabling the other day): https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

example error from https://github.com/crawl/crawl/runs/1413257173?check_suite_focus=true:
```
Prepend /usr/bin/ccache to $PATH
Error: Unable to process command '::add-path::/usr/bin/ccache' successfully.
Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Unexpected error attempting to determine if executable file exists '/usr/bin/ccache/cc': Error: ENOTDIR: not a directory, stat '/usr/bin/ccache/cc'
Unexpected error attempting to determine if executable file exists '/usr/bin/ccache/cc': Error: ENOTDIR: not a directory, stat '/usr/bin/ccache/cc'
```

I'm not fluent enough in GHA or typescript to figure out how to fix this, sorry. But it might be as simple as updating @actions/core. It actually looks like in https://github.com/alexjurkiewicz/setup-ccache/commit/3609e67c7474fbb8dedca537b71cb1f91afd64c5 this version did get bumped, so maybe crawl is just not using the right version? Edit: or perhaps the dist version needs to be rebuilt (however that is done) -- it looks like dist/index.js itself is still using `add-path`.

**Comment by alexjurkiewicz** [comment]
Try changing crawl to use "master" rather than "v1". Does that work?

**Comment by rawlins** [comment]
> Try changing crawl to use "master" rather than "v1". Does that work?

Looks like it's already using `alexjurkiewicz/setup-ccache@master`: https://github.com/crawl/crawl/blob/master/.github/workflows/ci.yml#L114

**Comment by alexjurkiewicz** [comment]
I forgot for JS actions you need to pre-compile your code. I pushed a12ee8530cc6df18b21057ea236e42c93debe030 which should fix this if you can try again?

**Comment by rawlins** [comment]
That worked, thanks!! Sample run: https://github.com/crawl/crawl/runs/1421652510?check_suite_focus=true

 I'll go ahead and close.
